# Federated Learning
#preload_model: True
#load_results: False
#preload_model_name: no_attack_new
#start_round: 100
#log_file: effectOfAttacker
#carry_attack: True
#carry_defence: False

preload_model: True
load_results: False
preload_model_name: no_attack_new
start_round: 99
log_file: defence_with
  
  
  _ratio_sibu
carry_attack: True
carry_defence: True

dataset: blood cell


total_clients: 70
client_num_proportion: 0.1
rounds: 100
dirichlet_alpha: 0.9

lr_decrease_epochs: [60, 99, 160, 200]
#lr_decrease_epochs: [0, 0, 10, 50]

# Server
global_lr: 1


# Benign client
batch_size: 32
benign_epochs: 2
momentum: 0.9

optimizer: SGD

# Malicious client
poisoning_label: 2
# 20 for CIFAR10
poisoning_num: 1
poisoning_epoch: 100
