# Federated Learning
preload_model: False
carry_attack: False
total_clients: 70
client_num_proportion: 0.2
rounds: 200
dirichlet_alpha: 0.9

lr_decrease_epochs: [60, 100, 160, 200]
#lr_decrease_epochs: [0, 0, 10, 50]

# Server
global_lr: 1


# Benign client
batch_size: 32
benign_learning_rate: 0.001
#benign_learning_rate: 0.05
#benign_decay: 0.005
benign_decay: 0.005
benign_epochs: 2
#momentum: 0.9
momentum: 0.2

# Malicious client
poisoning_label: 2
attacker_learning_rate: 0.01
attacker_decay: 0.0005
attacker_epochs: 15
# poisoning_scale: proportion of the batch which will be poisoned
poisoning_num: 1
poisoning_epoch: 100
