# Federated Learning
#preload_model: False
#load_results: False
#preload_model_name: no_attack_new
#start_round: 1
#log_file: testTrainAutoChangingCode
#carry_attack: False
#carry_defence: False

preload_model: False
load_results: False
preload_model_name: no_attack_new
start_round: 1
log_file: testTrainAutoChangingCode
carry_attack: False
carry_defence: False

dataset: blood cell


total_clients: 70
client_num_proportion: 0.2
rounds: 200
dirichlet_alpha: 0.9

lr_decrease_epochs: [100, 100, 160, 200]
#lr_decrease_epochs: [0, 0, 10, 50]

# Server
global_lr: 1


# Benign client
batch_size: 32
benign_epochs: 2
momentum: 0.9

optimizer: SGD
#optimizer: Adam
#log_file: new_Adam_start
#log_file: new_SGD_start_2
#log_file: SGD_09momentum
#log_file: SGD_09momentum_01
#log_file: Adam_last_layer
#log_file: testGoodTrain


# Malicious client
poisoning_label: 2
attacker_epochs: 15
poisoning_num: 1
poisoning_epoch: 101
