# Loading a pretrained model
preload_model: True
load_results: False
preload_model_name: blood_cell_round99

# What round the training is starting at. Useful when loading a model
start_round: 99

# Name of the log file
log_file: defence_with

# Carry backdoor attack
carry_attack: True

# Carry defence mechanism
carry_defence: True

# Which dataset to use
dataset: blood cell


total_clients: 70
# How many clients to use in each round
client_num_proportion: 0.1
rounds: 100
dirichlet_alpha: 0.9

lr_decrease_epochs: [60, 99, 160, 200]

# Server
global_lr: 1


# Benign client
batch_size: 32
benign_epochs: 2
momentum: 0.9

optimizer: SGD

# Malicious client
poisoning_label: 2
# 20 for CIFAR10
poisoning_num: 1
poisoning_epoch: 100
